Airtable Updates
move-coop/parsons pull request #1082
Opened 2024-06-24 12:35 UTC by codygordon

- [`airtable-python-wrapper` was renamed to `pyairtable` after v1.0](https://github.com/gtalarico/pyairtable/issues/125#issuecomment-891439661). Needed to update this eventually if we want to take advantage of newer features. Seems despite a couple method name changes that it's backwards compatible.
- Added new methods:
  - [update_records](https://pyairtable.readthedocs.io/en/stable/api.html#pyairtable.Table.batch_update)
  - [upsert_records](https://pyairtable.readthedocs.io/en/stable/api.html#pyairtable.Table.batch_upsert)
  - [delete_record](https://pyairtable.readthedocs.io/en/stable/api.html#pyairtable.Table.delete)
  - [delete_records](https://pyairtable.readthedocs.io/en/stable/api.html#pyairtable.Table.batch_delete) 
- Added `typecast` to `insert_record`

2024-06-24 13:59 UTC, codygordon commented
https://github.com/move-coop/parsons/issues/950

2024-06-24 14:02 UTC, codygordon commented
also working on addressing [this](https://github.com/move-coop/parsons/issues/758), which I can confirm is still an issue even in the updated lib.

the fix requires fetching the table schema and appending all `fields` to the call, which makes the tests a bit trickier

2024-06-27 20:25 UTC, shaunagm requested changes
This looks great, just one place that would be good to have a code comment as it's not clear what the code's doing. Once that's added I can merge this

2024-06-27 20:25 UTC, shaunagm commented on parsons/airtable/airtable.py
> +        if any(isinstance(row, dict) for row in table):
Can you add a comment here to clarify what's happening on these two lines?

2024-07-09 20:35 UTC, shaunagm approved these changes

2024-07-09 20:35 UTC, merged