Draft - refactor dbt utility for modularity
move-coop/parsons pull request #1095
Opened 2024-07-15 21:33 UTC by austinweisgrau

These changes uncouple the code for the dbt utility that runs a dbt command from the code that logs dbt commands. This allows for modular use of different loggers and a very flexible ability to customize logging.

TO DO:
- [ ] Improve naming of some of the classes for clarity
- [ ] Touch up the dbtLoggerMarkdown text formatting a bit

2024-11-04 16:49 UTC, elyse-weiss commented
I do not feel qualified to approve, but having the `requirements.txt` file updated as it is here, would be helpful for me separately!

2025-03-06 16:55 UTC, austinweisgrau commented
Finally fixed the build issue

2025-03-13 18:13 UTC, shaunagm commented on parsons/utilities/dbt/__init__.py
> +
These docs are good, but ideally we want to be able to surface them on the docs website. Maybe add a hook into the autodocs on this page? https://move-coop.github.io/parsons/html/stable/utilities.html#

2025-03-13 19:21 UTC, shaunagm requested changes
A couple minor requests/questions but overall looks good. I know @matthewkrausse is looking forward to seeing this merged so hope to get it over the finish line soon and promise not to be a blocker on my end :)

2025-03-13 19:21 UTC, shaunagm commented on parsons/utilities/dbt/dbt.py
> +        If raise_error is set, this method will raise an error if the dbt
Where is raise_error set? Where is it referenced? Is this an underlying dbt thing or is it part of this method/class?

2025-03-24 17:19 UTC, austinweisgrau commented on parsons/utilities/dbt/__init__.py
> +
I thiiink 8d56b8a5da5172597ab6b162cf34d0ec0f63a473 should do this

2025-03-25 17:38 UTC, merged