RockTheVote: add support for extended report
move-coop/parsons pull request #366
Opened 2020-09-04 23:53 UTC by dannyboy15

This adds the option to request the extended report which add a few extra fields. In addition, it adds support for the testing url.

h/t @natashamathur

2020-09-05 12:39 UTC, natashamathur commented
For context, the reason I set up the report_type parameter the way it is was because

The existing code did not include a report_type parameter, and I wanted to make sure requests without that parameter still went through to minimize downstream effects and
I wasn't sure if RTV was going to release more report types, or if it was always going to be just "extended" vs "normal/default".

Overall, this should add the ability to use the testing environment, and to pull an "extended" report.

2020-09-07 16:18 UTC, jburchard requested changes
This is really great. Just a few minor comments.

2020-09-07 16:18 UTC, jburchard commented on parsons/rockthevote/rtv.py
> +                "https://register.rockthevote.com/api/v4", headers=REQUEST_HEADERS)
Super picky, but can you move these URIs to the top of the script?

```
TESTING_URI = "https://staging.rocky.rockthevote.com/api/v4"
PRODUCTION_URI = "https://register.rockthevote.com/api/v4"
```

2020-09-07 16:18 UTC, jburchard commented on parsons/rockthevote/rtv.py
> +                The type of report to create. Currently only accepts "extended".
```
Currently only accepts ``extended``.
```
Also, could you explain what happens in the docs when it is left as ``None``?

2020-09-07 16:18 UTC, jburchard commented on parsons/rockthevote/rtv.py
> +                The type of report to run. Currently only accepts "extended".
Currently only accepts ``extended``.
```
Also, could you explain what happens in the docs when it is left as ``None``?

2020-09-08 13:12 UTC, jburchard approved these changes

2020-09-08 13:12 UTC, merged