Redshift:  update statupdate and compupdate copy options
move-coop/parsons pull request #372
Opened 2020-09-08 23:45 UTC by dannyboy15

This would change the default behavior of copying tables into Redshift. It would align more with the defaults that Redshift uses.

2020-09-09 23:37 UTC, eliotst commented
Thanks for this, @dannyboy15 ! This change seems reasonable to me, but I am not super familiar with the trade offs for these flags.

@schuyler1d or @jburchard do you have any thoughts on this? I know you two have done a lot of thinking around `compupdate` specifically, especially with regards to `upsert`. Do either of you have thoughts on defaults for `compupdate`?

2020-09-09 23:37 UTC, eliotst commented
I also want to flag the merge conflict on `test/test_redshift.py`

2020-09-11 06:14 UTC, dannyboy15 commented
I think at the very least we should merge in the change that can handle `statupdate=None`.

2020-09-11 06:17 UTC, dannyboy15 commented
As for the point about leaving the default as `True`, I wonder if there's any precedent there. Have other methods been implemented in such a way that they deviate from the underlying services default to encourage best practices or achieve optimization?

2020-12-07 18:54 UTC, jburchard requested changes
Just a couple of requests around documentation?

2020-12-07 18:54 UTC, jburchard commented on parsons/databases/redshift/redshift.py
> +                ``False`` explicitly sets ``statupate`` to off. Defaults to ``None``.
Please include a note telling the user that  

``If STATUPDATE is used, the current user must be either the table owner or a superuser.``

2020-12-07 18:54 UTC, jburchard commented on parsons/databases/redshift/redshift.py
> +                ``compupdate`` to off. Defaults to ``None``.
Perhaps explain to folks what happens if it is set to `None`. Or at least link to the redshift documentation?

2020-12-07 18:54 UTC, jburchard commented on parsons/databases/redshift/redshift.py
> +                ``False`` explicitly sets ``statupate`` to off. Defaults to ``None``.
Perhaps explain to folks what happens if it is set to None. Or at least link to the redshift documentation?

2021-03-01 15:24 UTC, SorenSpicknall approved these changes
This looks good to go now after the documentation additions.

2021-06-28 15:09 UTC, merged

2021-06-30 02:01 UTC, schuyler1d commented
Sorry I missed this prompt -- I saw a new github message after this was merged.
I noted observed compupdate performance here:
https://github.com/dannyboy15/parsons/blob/332c3a8ab82836d24fa5419c69b2126f55340ca7/parsons/databases/redshift/redshift.py#L775-L780
In this case, it looks like @dannyboy15 is helping to fix a bad past default in Parsons for everyone where I merely changed it for the upsert() use-case.  So I retroactively support this PR :-)

I do think Parsons should include best-practices rather than just API defaults -- an API is only as good as its implementation, and to make parsons performant we should help users around performance cliffs when we can (and often API implementations from vendors are dumb -- defaults aren't policy, but sometimes defaults for their own legacy/backwards-compatibility requirements)

In terms of precedent, there are a few optimizations in the action_kit driver (upload_table) depending on the shape of the data uploaded.