Redshift: Add dist/sort keys to upsert.
move-coop/parsons pull request #373
Opened 2020-09-09 00:54 UTC by jburchard

This PR does the following:

- Adds arguments that allow the user to set the dist/sort keys for an upsert. If the table does not previously exist, this will set the dist/sort keys. If the table exists, it will set the dist/sort keys for the staging table to the provided arguments.

- If the dist/sort key areguments are `None`, then it will set the primary_key as the dist/sort keys for the staging table.

The benefit of all of this should be that upserts should run faster whether the argument is passed or not, since the staging table will have a dist/sort key which will most likely be the same as the destination table.

2020-09-09 23:31 UTC, eliotst requested changes
Looks good.. just a couple comments about handling multiple primary keys.

2020-09-09 23:31 UTC, eliotst commented on parsons/databases/redshift/redshift.py
> +                          distkey=primary_key,
`primary_key` can be a list, but Redshift only allows for a single `distkey`. You could just pick one if there's more than one.. so `primary_keys[0]` (`primary_keys` is generated in line 738 and will always be a list)

2020-09-09 23:31 UTC, eliotst commented on parsons/databases/redshift/redshift.py
> +                          sortkey=primary_key,
Redshift allows multiple `sortkey`s, but the `RedshiftCreateTable` doesn't.. could you change line 206/207 in `parsons/databases/redshift/rs_create_table.py` to support a possible list while we're here?

2021-10-29 20:43 UTC, ChrisC commented
Updated in #588

2021-10-29 20:43 UTC, closed without merging