Docs: Update Bill.com
move-coop/parsons pull request #379
Opened 2020-09-09 06:53 UTC by rgriff23

- add Authentication Guide, improve Overview, improve Quickstart
- should check the boxes for Bill.com in #269

2020-09-09 14:04 UTC, jburchard requested changes

2020-09-09 14:04 UTC, jburchard commented on docs/bill_com.rst
> +- check whether two customers are the same
Possible uppercase these?

2020-09-09 14:48 UTC, jburchard approved these changes

2020-09-09 14:48 UTC, merged

2020-09-10 20:02 UTC, rgriff23 commented
@jburchard I just noticed Bill.com still needs to be checked off in the table in #269