Added functionality to Zoom class
move-coop/parsons pull request #461
Opened 2020-12-05 22:29 UTC by bzupnick

This is a PR for [this issue](https://github.com/move-coop/parsons/issues/459).

2020-12-07 13:26 UTC, eliotst commented
Thanks so much for this, @bzupnick ! We will take a look, and we should be able to provide a review in the next couple of days.

2020-12-08 15:27 UTC, jburchard requested changes
This is really great! Thank you.

Just a little minor doc styling to change and then we are good to go!

2020-12-08 15:27 UTC, jburchard commented on parsons/zoom/zoom.py
> +        Get meeting registrants
Add a period.*

* We could probably stand to have a style guide for documentation at some point.

2020-12-08 15:27 UTC, jburchard commented on parsons/zoom/zoom.py
> +        Get meeting registrants
Period.

2020-12-08 15:27 UTC, jburchard commented on parsons/zoom/zoom.py
> +        Get past meeting participants
Period.

2020-12-08 15:39 UTC, closed without merging

2020-12-08 15:39 UTC, bzupnick commented
migrated over to https://github.com/move-coop/parsons/pull/461