Cormac mobilecommons connector
move-coop/parsons pull request #730
Opened 2022-08-18 17:01 UTC by cmdelrio

Thank you Daniel! Let me know if I can clarify anything.

2022-08-18 22:25 UTC, dannyboy15 reviewed
This looks really good! I left comments mostly to tidy up the code, and I didn't see any logic error. Let me know if you have questions or want to me to explain something further.

2022-08-18 22:25 UTC, dannyboy15 commented on parsons/mobilecommons/mobilecommons.py
> +                page_params = params + f'&page={str(i)}'
same thing about using a dict for params (and about using ints in f-string) as above.

2022-08-18 22:25 UTC, dannyboy15 commented on parsons/mobilecommons/mobilecommons.py
> +                            f'of {limit}')
f-string implicitly convert ints to str

2022-08-18 22:25 UTC, dannyboy15 commented on parsons/mobilecommons/mobilecommons.py
> +                                               params=page_params)
same thing about params.

2022-08-18 22:25 UTC, dannyboy15 commented on parsons/mobilecommons/mobilecommons.py
> +                i += 1
if you switch to for loop remove this.

2022-08-18 22:25 UTC, dannyboy15 commented on parsons/mobilecommons/mobilecommons.py
> +        else:
One other approach would be to check in if there's an error at the top and if not then fetch the data. It looks a little cleaner and keep you core logic from being indent more than it has to.

```python
if response.status_code != 200:
    # do error handling here
    ...
    raise

# do your data fetching here.
for i in range(2, pages_to_get + 1):
    ...
```

2022-08-18 22:25 UTC, dannyboy15 commented on parsons/mobilecommons/mobilecommons.py
> +            :return:
Try to be consistent with the docstring formatting.

2022-08-18 22:25 UTC, dannyboy15 commented on parsons/mobilecommons/mobilecommons.py
> +        params = ''
if you use a dict for params, this should be fairly straightforward. you can also use the utility to parse dates.

```python
from parsons.utilities.datetime import parse_date

DATE_FMT = '%Y-%m-%d'
formatted_date = lambda x: parse_date(x).strftime(DATE_FMT)

...

params = {
    'start_time': formatted_date(start_time),
    'end_time': formatted_date(end_time),
}
```

2023-06-22 17:37 UTC, sharinetmc commented
Hi @cmdelrio! I just wanted to see where you were at making the changes danny suggested?

2023-06-22 19:39 UTC, cmdelrio commented
@sharinetmc I think I actually incorporated all of these. This connector is basically ready, but I haven't had the chance to write unit tests.

2023-06-22 19:44 UTC, shaunagm requested changes
Just updating this so it has the correct Github status of "request changes", let me know how if/when you've got time to update this, happy to help however I can.

2023-10-25 18:06 UTC, shaunagm commented
Closed in favor of #896

2023-10-25 18:06 UTC, closed without merging