Redshift.copy() can use AWS Session Token as part of auth variables
move-coop/parsons pull request #797
Opened 2023-03-17 20:59 UTC by austinweisgrau

A session token is sometimes a necessary component of AWS auth
credentials alongside an access key and secret key. This commit
enables a session token to be passed in the same ways that the other
credentials are passed:

- directly as part of copy_args
- through environmental variables

A test is added at `test/test_redshift.py::TestRedshift::test_get_creds_kwargs_with_token` to validate this behavior.

2023-03-17 21:09 UTC, austinweisgrau commented
Resolves #798

2023-05-08 15:49 UTC, Jason94 reviewed
Thanks for submitting the PR! I think this would be great to have.

2023-05-08 15:49 UTC, Jason94 commented on parsons/databases/redshift/redshift.py
> +        use_env_token=False,
I looked through the code, and I don't _think_ that this is being used. It gets passed around a bit, but ultimately `temp_s3_copy` is passing the field from the Redshift instance, not the parameters added in this PR, into the `S3` object. See rs_copy_table.py:L190.

And I agree with the way that it's technically implemented; the better design here is to defer to the `use_env_token` from the Redshift constructor. I think you can just remove the `use_env_token` parameter from the `copy` method, and the other methods where it's just being passed around.

2023-05-08 15:49 UTC, Jason94 commented on parsons/databases/redshift/redshift.py
> +                required if keys are stored as environmental variables.
Can you give the exact environmental variable the session token needs to be stored in as part of the documentation?

2023-05-08 15:49 UTC, Jason94 commented on parsons/databases/redshift/rs_copy_table.py
> +        use_env_token=False,
Same comment as above - is this `use_env_token` being used?

2023-06-22 17:52 UTC, sharinetmc commented
Hi @austinweisgrau, just wondering if you were able to get to follow-up on some of the changes Justin suggested?

2023-06-22 19:55 UTC, sharinetmc requested changes
Hi @austinweisgrau! Just changing the status to 'request changes'. Please let me know if you have any questions!

2024-06-21 00:23 UTC, closed without merging

2024-06-21 00:23 UTC, austinweisgrau commented
Closing this