Fix Salesforce query output
move-coop/parsons pull request #829
Opened 2023-06-02 20:10 UTC by sjwmoveon

The existing code did not match the method description and did not produce a useful result. Salesforce returns a set of nested dicts, similar to JSON; the new method reformats the nested ordered dicts using the json library, similar to describe_fields.

2023-06-02 20:20 UTC, crayolakat commented
@sjwmoveon Can you modify the tests to pass with this new change?

2023-06-02 20:21 UTC, crayolakat requested changes
@sjwmoveon Can you modify the tests to pass with this new change?

2023-06-02 20:44 UTC, sjwmoveon commented
Yes, thank you! Since the tests mocked everything out I assumed they would pass; clearly a bad assumption on my part.

2023-06-02 20:48 UTC, sjwmoveon commented
It passed locally, I'm not sure what's wrong here.

2023-06-05 21:50 UTC, crayolakat approved these changes

2023-06-05 21:51 UTC, merged