Add Events Helpers to PDI Connector
move-coop/parsons pull request #865
Opened 2023-08-09 16:47 UTC by IanRFerguson

Adding helpers written by @cmdelrio to the `Events()` object. These functions are inherited by the `PDI()` connector and will be available post-authentication

2023-08-09 18:21 UTC, cmdelrio approved these changes
lgtm!

2023-08-10 00:11 UTC, IanRFerguson commented
@shaunagm I've tested this locally and it's returning data in the anticipated format, let me know if you have any questions

2023-08-10 00:12 UTC, IanRFerguson commented
Marking this as "medium priority" as it's blocking a sync-in from Mobilize

2023-08-10 02:03 UTC, shaunagm requested changes
These need docstrings, otherwise they won't appear in the documentation. They should also have automated tests written for them. If it's important enough you can merge as-is and do a follow-up PR with docs and tests but be forewarned I will hound you for it ;)

2023-08-10 02:03 UTC, shaunagm commented on parsons/pdi/events.py
> +    def get_event_activity_assignments(self, start_date, end_date, expand, limit=None):
Limit is not getting used here?

2023-08-15 19:28 UTC, Jason94 commented on parsons/pdi/events.py
> +        `Returns`:
Missing `Returns` doc

2023-08-15 19:57 UTC, IanRFerguson commented on parsons/pdi/events.py
> +        `Returns`:
thanks Jason!

2023-08-16 19:56 UTC, shaunagm approved these changes
Looks great, thanks for adding the docs & tests

2023-08-16 19:56 UTC, merged