Resolves #741 : Deprecate Slack chat.postMessage `as_user` argument and allow for new authorship arguments
move-coop/parsons pull request #891
Opened 2023-09-24 23:13 UTC by angloyna

This PR adds a deprecation warning for usage of the `as_user` argument in calls to `chat.postMessage`, allows the user to see failed Slack API `deprecated_argument` responses, and facilitates usage of the new Slack authorship customization arguments `username`, `icon_url`, and `icon_emoji` using optional keyword arguments (See: https://api.slack.com/methods/chat.postMessage#authorship)

`as_user` will still be passed on to the slack request and will still fail if the user passes in `as_user=False`, but the user should see more information in the failed response now.

2023-09-25 15:02 UTC, Jason94 requested changes

2023-09-25 15:51 UTC, angloyna commented on parsons/notifications/slack.py
> +                This is a deprecated argument. Use optional username, icon_url, and icon_emoji
Yeah, now that you're mention it, I agree. I'm tending toward option #1

2023-09-26 00:14 UTC, angloyna commented on parsons/notifications/slack.py
> +                This is a deprecated argument. Use optional username, icon_url, and icon_emoji
change made

2023-10-25 18:02 UTC, merged

2023-10-25 18:02 UTC, shaunagm commented
Thank you so much, @angloyna and sorry for the delay in merging!