Migrate from psycopg2 to psycopg3
move-coop/parsons pull request #987
Opened 2024-02-06 19:07 UTC by austinweisgrau

psycopg3 is mostly built as a drop-in upgrade from psycopg2.
Differences are detailed here: https://www.psycopg.org/psycopg3/docs/basic/from_pg2.html

One major DX improvement is that Ctrl-C can now cancel a running
query. With psycopg2, the python process can be killed but a running
query usually could not be killed (without knowing the PID and running
`pg_cancel_backend(pid)` from a separate connection), to the immediate
regret of all we who sometimes accidentally execute an unfortunately
large query.

2024-02-06 20:31 UTC, shaunagm commented
Looks like there are some file conflicts? Also, I thought we'd fixed it so the tests would get run against PRs to major-release?

If we can get this to run the tests, and the tests pass, that'd be great. It's especially important for a change to psycopg which has historically caused a huge amount of installation errors. Actually it'd be great if we could test this against an M1 mac, @austinweisgrau do you happen to have one you could test manually?

2024-02-06 20:34 UTC, shaunagm requested changes
I'm responding with 'request changes' because we need to figure out how to get the tests run on this (see more detail in other comment)

2024-02-07 00:00 UTC, austinweisgrau commented
I believe the major release branch needs to be brought up to date and that should simplify the diffs considerably

2024-02-07 16:56 UTC, austinweisgrau commented
Ahh it needs more configuration anyways to work propertly, making this a DRAFT for now

2026-09-17 16:32 UTC, shaunagm commented
closing this as superseded by #1903

2026-09-17 16:32 UTC, closed without merging